import 'dart:math';

enum Suit { clubs, diamonds, hearts, spades }
enum Rank { ace, two, three, four, five, six, seven, eight, nine, ten, jack, queen, king }
class PlayingCard { final Suit suit; final Rank rank; const PlayingCard(this.suit,this.rank); bool get red=>suit==Suit.diamonds||suit==Suit.hearts; String get symbol=>const {Suit.clubs:'♣',Suit.diamonds:'♦',Suit.hearts:'♥',Suit.spades:'♠'}[suit]!; String get label=>'${const ['A','2','3','4','5','6','7','8','9','10','J','Q','K'][rank.index]}$symbol'; }
class Deck { final List<PlayingCard> cards=[for(final s in Suit.values) for(final r in Rank.values) PlayingCard(s,r)]; void shuffle([Random? random])=>cards.shuffle(random??Random()); PlayingCard draw()=>cards.removeLast(); }
enum PokerCategory { highCard,pair,twoPair,threeOfAKind,straight,flush,fullHouse,fourOfAKind,straightFlush }
class PokerScore implements Comparable<PokerScore>{final PokerCategory category;final List<int> tiebreak;const PokerScore(this.category,this.tiebreak);@override int compareTo(PokerScore o){final c=category.index.compareTo(o.category.index);if(c!=0)return c;for(var i=0;i<tiebreak.length&&i<o.tiebreak.length;i++){final d=tiebreak[i].compareTo(o.tiebreak[i]);if(d!=0)return d;}return 0;}}
class PokerEvaluator {
 static PokerScore evaluate(List<PlayingCard> cards){final ranks=cards.map((c)=>c.rank.index+2).toList()..sort((a,b)=>b.compareTo(a));final counts=<int,int>{};for(final r in ranks)counts[r]=(counts[r]??0)+1;final flush=cards.length==5&&cards.every((c)=>c.suit==cards.first.suit);final unique=ranks.toSet().toList()..sort((a,b)=>b.compareTo(a));var straightHigh=unique.length==5&&unique.first-unique.last==4?unique.first:0;if(unique.length==5&&unique.contains(14)&&unique.contains(2)&&unique.contains(3)&&unique.contains(4)&&unique.contains(5))straightHigh=5;final groups=counts.entries.toList()..sort((a,b){final c=b.value.compareTo(a.value);return c!=0?c:b.key.compareTo(a.key);});if(straightHigh>0&&flush)return PokerScore(PokerCategory.straightFlush,[straightHigh]);if(groups.first.value==4)return PokerScore(PokerCategory.fourOfAKind,[groups.first.key,groups[1].key]);if(groups.first.value==3&&groups[1].value==2)return PokerScore(PokerCategory.fullHouse,[groups.first.key,groups[1].key]);if(flush)return PokerScore(PokerCategory.flush,ranks);if(straightHigh>0)return PokerScore(PokerCategory.straight,[straightHigh]);if(groups.first.value==3)return PokerScore(PokerCategory.threeOfAKind,[groups.first.key,...groups.skip(1).map((e)=>e.key)]);if(groups.first.value==2&&groups[1].value==2){final p=[groups[0].key,groups[1].key]..sort((a,b)=>b.compareTo(a));return PokerScore(PokerCategory.twoPair,[...p,groups[2].key]);}if(groups.first.value==2)return PokerScore(PokerCategory.pair,[groups.first.key,...groups.skip(1).map((e)=>e.key)]);return PokerScore(PokerCategory.highCard,ranks);}
}
class PokerRound { final Deck deck=Deck();final List<PlayingCard> community=[],player=[],bot=[];PokerRound(){deck.shuffle();}void deal(){deck.cards..clear()..addAll([for(final s in Suit.values) for(final r in Rank.values) PlayingCard(s,r)]);deck.shuffle();player.clear();bot.clear();community.clear();player.addAll([deck.draw(),deck.draw()]);bot.addAll([deck.draw(),deck.draw()]);community.addAll([deck.draw(),deck.draw(),deck.draw()]);}void turn()=>community.add(deck.draw());void river()=>community.add(deck.draw());PokerScore? playerScore(){if(community.length<3)return null;return PokerEvaluator.evaluate(PokerHand.bestFive([...player,...community]));}}
class PokerHand { static List<PlayingCard> bestFive(List<PlayingCard> cards){if(cards.length<=5)return [...cards];PokerScore? best;List<PlayingCard> bestCards=[];for(var a=0;a<cards.length-4;a++){for(var b=a+1;b<cards.length-3;b++){for(var c=b+1;c<cards.length-2;c++){for(var d=c+1;d<cards.length-1;d++){for(var e=d+1;e<cards.length;e++){final hand=[cards[a],cards[b],cards[c],cards[d],cards[e]];final score=PokerEvaluator.evaluate(hand);if(best==null||score.compareTo(best)>0){best=score;bestCards=hand;}}}}}}return bestCards;}}
class BlackjackRound {final Deck deck=Deck();final List<PlayingCard> player=[],dealer=[];BlackjackRound(){deck.shuffle();}void deal(){deck.cards..clear()..addAll([for(final s in Suit.values) for(final r in Rank.values) PlayingCard(s,r)]);deck.shuffle();player.clear();dealer.clear();player.addAll([deck.draw(),deck.draw()]);dealer.addAll([deck.draw(),deck.draw()]);}static int value(List<PlayingCard> cards){var total=0,aces=0;for(final c in cards){if(c.rank==Rank.ace){total+=11;aces++;}else if(c.rank.index>=Rank.jack.index)total+=10;else total+=c.rank.index+1;}while(total>21&&aces-->0)total-=10;return total;}}
class ClassicCardGames {static const games=['Texas Hold’em Poker','Blackjack','Klondike Solitaire','FreeCell','Hearts','Spades','Crazy Eights','War'];}
